version: "2"         # required to adjust maintainability checks
plugins:
 eslint:
  enabled: true
  channel: eslint-5
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: true
    config:
      threshold: 100
  identical-code:
    enabled: false
  similar-code:
    config:
      threshold: 100
exclude_patterns:
- "**/*.spec.js"
