language: node_js

before_install:
  - npm install -g npm@5.6.0

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "stable"

script:
  - npm run validate
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
