language: node_js

before_install:
  - npm install -g npm@6.4.1

node_js:
  - "8"
  - "9"
  - "10"
  - "stable"

script:
  - npm run validate
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
